//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLiteProvider {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MembershipSql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MembershipSql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SQLiteProvider.Sql.MembershipSql", typeof(MembershipSql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE User SET Password = $Password, LastPasswordChangedDate = datetime(&apos;now&apos;,&apos;utc&apos;) WHERE Username = $Username AND AppID = $AppID;.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE User SET PasswordQuestion = $Question, PasswordAnswer = $Answer WHERE Username = $Username AND AppID = $AppID;.
        /// </summary>
        internal static string ChangePasswordQA {
            get {
                return ResourceManager.GetString("ChangePasswordQA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO User
        ///(
        ///	Username,
        ///	Password,
        ///	Email,
        ///	PasswordQuestion,
        ///	PasswordAnswer,
        ///	IsApproved,
        ///	Comment,
        ///	CreationDate,
        ///	LastPasswordChangedDate,
        ///	LastActivityDate,
        ///	AppID,
        ///	IsLockedOut,
        ///	LastLockedOutDate,
        ///	FailedPasswordAttemptCount,
        ///	FailedPasswordAttemptWindowStart,
        ///	FailedPasswordAnswerAttemptCount,
        ///	FailedPasswordAnswerAttemptWindowStart
        ///)
        ///Values(
        ///	$Username,
        ///	$Password,
        ///	$Email,
        ///	$PasswordQuestion,
        ///	$PasswordAnswer,
        ///	$IsApproved,
        ///	&apos;&apos;,
        ///	datetime(&apos;now&apos;,&apos;utc&apos;),
        ///	datetime( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateUser {
            get {
                return ResourceManager.GetString("CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM User WHERE Username = $Username AND AppID = $AppID;.
        /// </summary>
        internal static string DeleteUser {
            get {
                return ResourceManager.GetString("DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT UserID, Username, Email, PasswordQuestion,
        ///Comment, IsApproved, IsLockedOut, CreationDate, LastLoginDate,
        ///LastActivityDate, LastPasswordChangedDate, LastLockedOutDate 
        ///FROM User 
        ///WHERE Email LIKE $EmailSearch AND AppID = $AppID 
        ///ORDER BY Username Asc
        ///LIMIT $Count, $Skip .
        /// </summary>
        internal static string FindUsersByEmail {
            get {
                return ResourceManager.GetString("FindUsersByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT UserID, Username, Email, PasswordQuestion,
        ///Comment, IsApproved, IsLockedOut, CreationDate, LastLoginDate,
        ///LastActivityDate, LastPasswordChangedDate, LastLockedOutDate 
        ///FROM User 
        ///WHERE Username LIKE $UsernameSearch AND AppID = $AppID
        ///ORDER BY Username Asc
        ///LIMIT $Count, $Skip .
        /// </summary>
        internal static string FindUsersByName {
            get {
                return ResourceManager.GetString("FindUsersByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	UserID, Username, Email, PasswordQuestion, Comment, IsApproved, IsLockedOut, CreationDate, LastLoginDate, LastActivityDate, LastPasswordChangedDate, LastLockedOutDate 
        ///FROM 
        ///	User 
        ///WHERE 
        ///	AppID = $AppID 
        ///ORDER BY 
        ///	Username Asc
        ///LIMIT
        ///	$Skip, $Count.
        /// </summary>
        internal static string GetAppUsers {
            get {
                return ResourceManager.GetString("GetAppUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Password, PasswordAnswer, IsLockedOut FROM User WHERE Username = $Username AND AppID = $AppID;.
        /// </summary>
        internal static string GetPassword {
            get {
                return ResourceManager.GetString("GetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT UserID, Username, Email, PasswordQuestion,
        ///Comment, IsApproved, IsLockedOut, CreationDate, LastLoginDate,
        ///LastActivityDate, LastPasswordChangedDate, LastLockedOutDate
        ///FROM User WHERE UserID = $UserID;.
        /// </summary>
        internal static string GetUserByID {
            get {
                return ResourceManager.GetString("GetUserByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	UserID, Username, Email, PasswordQuestion, Comment, 
        ///	IsApproved, IsLockedOut, CreationDate, LastLoginDate, 
        ///	LastActivityDate, LastPasswordChangedDate, LastLockedOutDate 
        ///FROM 
        ///	User 
        ///WHERE 
        ///	Username = $Username AND AppID = $AppID;.
        /// </summary>
        internal static string GetUserByName {
            get {
                return ResourceManager.GetString("GetUserByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Username  FROM User WHERE Email = $Email AND AppID = $AppID;.
        /// </summary>
        internal static string GetUserNameByEmail {
            get {
                return ResourceManager.GetString("GetUserNameByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Count(*) FROM User WHERE LastActivityDate &gt; $CompareDate AND AppID = $AppID;.
        /// </summary>
        internal static string GetUsersOnline {
            get {
                return ResourceManager.GetString("GetUsersOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE User
        ///SET IsLockedOut = $IsLockedOut, LastLockedOutDate = datetime(&apos;now&apos;,&apos;utc&apos;)
        ///WHERE Username = $Username AND AppID = $AppID.
        /// </summary>
        internal static string LockOutUser {
            get {
                return ResourceManager.GetString("LockOutUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT FailedPasswordAttemptCount, 
        ///FailedPasswordAttemptWindowStart, 
        ///FailedPasswordAnswerAttemptCount, 
        ///FailedPasswordAnswerAttemptWindowStart 
        ///FROM User 
        ///WHERE Username = $Username AND AppID = $AppID.
        /// </summary>
        internal static string QueryFailureCount {
            get {
                return ResourceManager.GetString("QueryFailureCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT PasswordAnswer, IsLockedOut FROM User WHERE Username = $Username AND AppID = $AppID;.
        /// </summary>
        internal static string QueryPasswordReset {
            get {
                return ResourceManager.GetString("QueryPasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE User SET Password = $Password, LastPasswordChangedDate = datetime(&apos;now&apos;,&apos;utc&apos;) WHERE Username = $Username AND AppID = $AppID AND IsLockedOut = 0.
        /// </summary>
        internal static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE User 
        ///SET IsLockedOut = 0, LastLockedOutDate = datetime(&apos;now&apos;,&apos;utc&apos;) 
        ///WHERE Username = $Username AND AppID = $AppID;.
        /// </summary>
        internal static string UnlockUser {
            get {
                return ResourceManager.GetString("UnlockUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE User 
        ///SET LastActivityDate = datetime(&apos;now&apos;,&apos;utc&apos;) 
        ///WHERE UserID = $UserID;.
        /// </summary>
        internal static string UpdateAccessTimeByID {
            get {
                return ResourceManager.GetString("UpdateAccessTimeByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE User 
        ///SET FailedPasswordAnswerAttemptCount = $Count
        ///WHERE Username = $Username AND AppID = $AppID.
        /// </summary>
        internal static string UpdateAnswerFailureCount {
            get {
                return ResourceManager.GetString("UpdateAnswerFailureCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE User 
        ///SET FailedPasswordAnswerAttemptCount = $Count, 
        ///FailedPasswordAnswerAttemptWindowStart = datetime(&apos;now&apos;,&apos;utc&apos;) 
        ///WHERE Username = $Username AND AppID = $AppID.
        /// </summary>
        internal static string UpdateAnswerFailureCountStart {
            get {
                return ResourceManager.GetString("UpdateAnswerFailureCountStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE User SET LastLoginDate = datetime(&apos;now&apos;,&apos;utc&apos;) WHERE Username = $Username AND AppID = $AppID.
        /// </summary>
        internal static string UpdateLastLoginDate {
            get {
                return ResourceManager.GetString("UpdateLastLoginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE User 
        ///SET FailedPasswordAttemptCount = $Count
        ///WHERE Username = $Username AND AppID = $AppID.
        /// </summary>
        internal static string UpdatePasswordFailureCount {
            get {
                return ResourceManager.GetString("UpdatePasswordFailureCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE User 
        ///SET FailedPasswordAttemptCount = $Count, 
        ///FailedPasswordAttemptWindowStart = datetime(&apos;now&apos;,&apos;utc&apos;) 
        ///WHERE Username = $Username AND AppID = $AppID.
        /// </summary>
        internal static string UpdatePasswordFailureCountStart {
            get {
                return ResourceManager.GetString("UpdatePasswordFailureCountStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE User
        ///SET Email = $Email, Comment = $Comment,
        ///IsApproved = $IsApproved
        ///WHERE Username = $Username AND AppID = $AppID.
        /// </summary>
        internal static string UpdateUser {
            get {
                return ResourceManager.GetString("UpdateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE User SET LastActivityDate = datetime(&apos;now&apos;,&apos;utc&apos;) WHERE Username = $Username AND AppID = $AppID;.
        /// </summary>
        internal static string UpdateUserAccessTimeByName {
            get {
                return ResourceManager.GetString("UpdateUserAccessTimeByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Password, IsApproved FROM User WHERE Username = $Username AND AppID = $AppID AND IsLockedOut = 0.
        /// </summary>
        internal static string ValidateUser {
            get {
                return ResourceManager.GetString("ValidateUser", resourceCulture);
            }
        }
    }
}
