//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLiteProvider {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SiteMapSql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SiteMapSql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SQLiteProvider.Sql.SiteMapSql", typeof(SiteMapSql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select NodeID, Title, Description, Url from SiteMapNode where AppID = $AppID and Parent = $ParentID;.
        /// </summary>
        internal static string GetNodeByParentID {
            get {
                return ResourceManager.GetString("GetNodeByParentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select NodeID Title, Description, Url from SiteMapNode where AppID = $AppID and Url like $Url;.
        /// </summary>
        internal static string GetNodeByUrl {
            get {
                return ResourceManager.GetString("GetNodeByUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select RoleName from Role
        ///Inner Join SiteMapNodeRoles on Role.RoleID = SiteMapNodeRoles.RoleID and Role.AppID = SiteMapNodeRoles.AppID
        ///Where SiteMapNodeRoles.NodeID = $NodeID and Role.AppID = $AppID;.
        /// </summary>
        internal static string GetNodeRoles {
            get {
                return ResourceManager.GetString("GetNodeRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select NodeID, Title, Description, Url, Parent from SiteMapNode where AppID = $AppID order by Parent;.
        /// </summary>
        internal static string GetNodes {
            get {
                return ResourceManager.GetString("GetNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Parent.NodeID, Parent.Title, Parent.Description, Parent.Url from SiteMapNode Parent
        ///left join SiteMapNode Child on Parent.NodeID = Child.Parent and Parent.AppID = Child.AppID
        ///where Child.AppID = $AppID and Child.NodeID = $NodeID;.
        /// </summary>
        internal static string GetParentByNodeID {
            get {
                return ResourceManager.GetString("GetParentByNodeID", resourceCulture);
            }
        }
    }
}
